version: '3'

services:
  db1:
    image: mysql:8.0.31
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: alphamed
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root